version: "3"
services:

  api:
    build:
      context: orderbook
      dockerfile: Dockerfile
    ports:
    restart: on-failure

  youtube:
    build:
      context: nlp
      dockerfile: Dockerfile
    restart: on-failure